### ISSUE TITLE
Multiple error messages displayed

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#13]
**Describe the bug**
Clicking the BORROW button when there's not enough liquidity produces an error. Continually clicking creates multiple error messages.

**To Reproduce**
1. Select YFI to borrow
2. Click the 80% link
3. Click the borrow button multiple times

**Expected behavior**
The error message displayed could be handled better, and/or don't enable the borrow button if there is not enough liquidity to fulfil the transaction

**Screenshots**
https://drive.google.com/file/d/1-Cxn4hVasGJmnAgPynx3jmMSjLW6GzA1/view?usp=sharing

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0x46FFB3a528b3CCfb7fE590fE0f843f3fd57e6075

**Additional context**
N/A

**Comment by harv-singh** [comment]
Internal issue #359 raised

**Comment by harv-singh** [comment]
Confirmed with the developer this is expected behaviour as the UI does handle the error

**Comment by ReluctantHodler** [comment]
Thanks for confirming I will close
