### ISSUE TITLE
Fail with error 'Insufficient balance'

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#14]
**Describe the bug**
I borrowed 2500 USDT. I then attempted to pay back to 2500 immediately and even though I had the 2500 in my wallet I had just borrowed, an error was displayed in Metamask and the transaction failed - https://rinkeby.etherscan.io/tx/0xc847dd36ad0aba9655b5a8499ea5e6f2ac57d64a6e22d00eee292210a45ed6b6

**To Reproduce**
1. Borrow 2500 USDT
2. Immediately attempt repay
3. Error visible in Metamask confirmation widow
4. Transaction errored - 

**Expected behavior**
I would expect to be able to repay a borrowed amount when the funds are available in my wallet.

**Screenshots**
![Screenshot 2021-04-13 at 23 24 02](https://user-images.githubusercontent.com/82473057/114629573-bf254500-9cb0-11eb-81c2-ac239aac7d38.png)
![Screenshot 2021-04-13 at 23 25 14](https://user-images.githubusercontent.com/82473057/114629585-c3516280-9cb0-11eb-8255-aede2bcb2335.png)
![Screenshot 2021-04-13 at 23 26 12](https://user-images.githubusercontent.com/82473057/114629592-c77d8000-9cb0-11eb-9fca-8486c66f9774.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0x46FFB3a528b3CCfb7fE590fE0f843f3fd57e6075

**Additional context**
N/A

**Comment by ReluctantHodler** [comment]
Just went back in and noticed it's now showing the Currently Borrowing amount as 2500.00809 which is odd as I definitely only borrowed 2500 USDT

![Screenshot 2021-04-13 at 23 37 45](https://user-images.githubusercontent.com/82473057/114629951-6bffc200-9cb1-11eb-80fe-0ccb17f249da.png)

**Comment by ReluctantHodler** [comment]
I then sourced some additional USDT from the Faucet so I had more than enough to pay off the borrowed amount. The repayment then worked perfectly, although was for more than my original borrowed amount of 2500 USDT. 

https://rinkeby.etherscan.io/tx/0x2fbcb01f1930122d18924586f5c9a39d5a4398f7122c47bdef0bcf85c2bc7cab

Take a look that the Tokens Transferred though, doesn't match the amount repaid.

![Screenshot 2021-04-13 at 23 39 45](https://user-images.githubusercontent.com/82473057/114630121-c6008780-9cb1-11eb-9e19-f46e17e060d6.png)

**Comment by Jag1899** [comment]
This additional .00809 is the interest added for borrowing the asset. 

_The Borrow Rate — Borrowers owe the prevailing interest rate of the asset they are borrowing._

**Comment by Jag1899** [comment]
Please close

**Comment by ReluctantHodler** [comment]
Makes sense. Thanks for clarifying
