### ISSUE TITLE
Insufficient Wallet Balance

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#15]
**Describe the bug**
When attempting to Supply total USDT balance from my wallet clicking the **Max** button truncates the value to 5 decimal places. The Wallet Balance is actually 999.990054 but as soon as you manually override the number you get the **_Insufficient Wallet Balance_** message displayed.

**To Reproduce**
1. Select USDT
2. Supply Max amount
3. Add additional decimal place to account for balance in wallet

**Expected behavior**
I should be able to supply the token total available in my wallet.

**Screenshots**
![Screenshot 2021-04-13 at 23 46 19](https://user-images.githubusercontent.com/82473057/114631261-27c1f100-9cb4-11eb-8494-8a8b120f1c07.png)
![Screenshot 2021-04-13 at 23 47 35](https://user-images.githubusercontent.com/82473057/114631273-2b557800-9cb4-11eb-9917-1052f0e0d968.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0x46FFB3a528b3CCfb7fE590fE0f843f3fd57e6075

**Additional context**
It feels like a rounding issue as only 5dp seem to be used across the site. I thin the full fidelity of the token should be used. I think this is also causing issues when Repaying loans too.

**Comment by harveerenergy** [comment]
Internal bug raised #365

**Comment by hskainth** [comment]
@ReluctantHodler  Verified as fixed internally, please close.

**Comment by ReluctantHodler** [comment]
OK thanks!
