### ISSUE TITLE
Overpayment Attempt Allowed

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#16]
**Describe the bug**
I borrowed 2655.06469 USDC. I then tried to repay, but overpay. The UI allowed me to do this, however Metamask warned of an error. I was able to process confirm the transaction in Metamask which then resulted in a failure and error - https://rinkeby.etherscan.io/tx/0xb132eed5519450dd7908609b44b6562dbd2a686c08bbebdc31e485f016e69e57

**To Reproduce**
1. Repay more than the borrowed amount

**Expected behavior**
I would expect the app to restrict repayment up to the amount borrowed.

**Screenshots**
![Bug 07a](https://user-images.githubusercontent.com/82473057/114632051-b84d0100-9cb5-11eb-923e-f9a65cb660aa.png)
![Bug 07b](https://user-images.githubusercontent.com/82473057/114632062-bedb7880-9cb5-11eb-97a4-765a32d5584d.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0x46FFB3a528b3CCfb7fE590fE0f843f3fd57e6075

**Additional context**

**Comment by harv-singh** [comment]
@ReluctantHodler can you try this scenario again please? The latest release to staging contained a fix to show the user they cannot do this, see below:
![Screenshot 2021-04-14 at 10 50 24](https://user-images.githubusercontent.com/44998024/114691193-50c39f80-9d0f-11eb-9be0-f74bc148a007.png)
^ from https://ledger-stage.unfederalreservetesting.com/

**Comment by ReluctantHodler** [comment]
Yes will check later today

**Comment by ReluctantHodler** [comment]
I can confirm this issue is fixed. :o)
