### ISSUE TITLE
No liquidation event even when 100.2% borrowed

### ISSUE THREAD

**Issue by UnCzechReserve** [UnFederalReserve/ReserveLendingAlphaTesters#27]
**Describe the bug**
I borrowed 100% but cant seem to see the liquidation event happening. 

**To Reproduce**
1. Borrow 100% 

**Expected behavior**
A liquidation event would occur?

**Screenshots**
![image](https://user-images.githubusercontent.com/82503926/115019977-30841400-9eba-11eb-8ef0-b27aeb5024ac.png)

**Wallet Version (please complete the following information):**
 - Wallet: Metamask
 - Public Address: 0x5c16c5AE6EEb21637C02B9C87AB54d9AE8C1Fac2

**Additional context**
Maybe it needs to be 100.1% .. i just thought this would lock my account or something... lets wait and see.

**Comment by UnCzechReserve** [comment]
![image](https://user-images.githubusercontent.com/82503926/115024917-041fc600-9ec1-11eb-8dc1-3bc84bd9da88.png)

**Comment by hskainth** [comment]
This has been raised internally before and has been closed as expected behaviour, please close issue.

See https://compound.finance/docs/ctokens#liquidate-borrow for more info

**Comment by LearnPolkadot** [comment]
See https://compound.finance/docs/ctokens#liquidate-borrow for more info
