### ISSUE TITLE
Provide Liquidity & Volume Statistics 

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#30]
**Is your feature request related to a problem? Please describe.**
Provide clear and easy to access statistics on the platform Liquidity & Volume.

**Describe the solution you'd like**
Bancor do a great job of providing transparent statistics around each of their liquidity pools. Would be great if you cold think about providing this pool/platform meta data.

![Screenshot 2021-04-16 at 14 02 26](https://user-images.githubusercontent.com/82473057/115028707-17309700-9ebd-11eb-835c-fd88f0813cec.png)

**Describe alternatives you've considered**
N/A

**Additional context**
Would allow users of the platform access to information to help them make an informed decision about when considering supplying their assets.

**Comment by hskainth** [comment]
Internal issue 385 exists for this.

**Comment by ReluctantHodler** [comment]
@hskainth I will close this ticket then. Thanks.
