### ISSUE TITLE
Distribution APY AAVE, SUSHI, LINK

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#34]
**Describe the bug**
Distribution APY shows 0% for AAVE, SUSHI, and LINK

**To Reproduce**
1. Go to Supply Market
2. Click on AAVE, SUSHI, or LINK
3. See 0% Distribution APY

**Expected behavior**
This maybe intended to be 0 but all other assets have some sort of Distribution APY. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71201055/115293720-a8a24200-a125-11eb-841e-3f83e71845d7.png)
![image](https://user-images.githubusercontent.com/71201055/115293756-b22baa00-a125-11eb-93f1-d2b6e06d5703.png)
![image](https://user-images.githubusercontent.com/71201055/115293765-b6f05e00-a125-11eb-8801-6599eae29a32.png)

Desktop (please complete the following information):

OS: Windows 10 Pro - 20H2
Browser: Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Wallet Version (please complete the following information):
MM - MetaMask - 9.3.0
CB - Coinbase - 23.6.363

**Additional context**
na

**Comment by dpiatti** [comment]
i saw this as well but believe no distribution APY for those tokens was setup?

**Comment by hskainth** [comment]
@LearnPolkadot This is not an issue, documentation will be available shortly which covers this behaviour. Please close.

**Comment by LearnPolkadot** [comment]
Non-issue
