### ISSUE TITLE
Please check Net APY Calculation

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#35]
**Describe the bug**
I'm not 100% certain this is a bug, but based on the calculation I had been provided with by Mirza (https://gist.github.com/ajb413/a6f89486ec5485746cd5eac1e10e4fc2) I was coming up with **-1.08%** Net APY and not the  0.69% displayed.

**To Reproduce**
1. See the attached screenshot
2. Use the calculation provided https://gist.github.com/ajb413/a6f89486ec5485746cd5eac1e10e4fc2
3. Check APY displayed in screenshot against your calc

**Expected behavior**
Just need to confirm the Net APY is being calculated as expected.

**Screenshots**

![Screenshot 2021-04-20 at 15 00 22](https://user-images.githubusercontent.com/82473057/115409772-f7b1ab00-a1e9-11eb-9fa3-99d9cbe93095.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0xCa949793838756D06c2f9F273fEa9dD365393AB7

**Additional context**
n/a

**Comment by harv-singh** [comment]
Thanks for raising  - there is an existing bug raised internally for this #395

**Comment by ReluctantHodler** [comment]
Thanks for the feedback. I will close as requested.
