### ISSUE TITLE
Decimal precision difference

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#37]
**Describe the bug**
The precision for the Borrow & Supply numbers differ. The borrow dialog defaults to 6dp whilst the supply dialog defaults to 5dp.

**To Reproduce**
1. View the supply dialog and click the max button
2. View the borrow dialog and click the 80% button

**Expected behavior**
Expect consistent decimal precision to be used throughout the app.

**Screenshots**
<img width="1047" alt="Screenshot 2021-04-21 at 00 01 13" src="https://user-images.githubusercontent.com/82473057/115474431-4f293880-a235-11eb-9ad0-7d704b28b30d.png">

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0x9B0Fff2102d23D25F541684c8109EFa7D91EE11c

**Additional context**
n/a

**Comment by harv-singh** [comment]
Internal issue #405 has been raised

**Comment by hskainth** [comment]
Dev feedback - It's not a bug. You can have all kinds of precisions for different values. For example 0.2, 0.45, 1.343543. It should not be all the same for sure. 

@ReluctantHodler  Please close issue.

**Comment by ReluctantHodler** [comment]
Why would the same asset have different precision? Either way, surely the precision across the app should be consistent, no?

**Comment by hskainth** [comment]
@ReluctantHodler this would be because your supply and borrow balances are not the same and can have different values, locking this would not cater for all eventualities.

**Comment by hskainth** [comment]
internal issue closed as invalid @ReluctantHodler please close.

**Comment by ReluctantHodler** [comment]
OK closing, but not 100% convinced.
