### ISSUE TITLE
Failed to claim total amount available to claim

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/ReserveLendingAlphaTesters#39]
**Describe the bug**
I have 3 test wallets. This one has been building up eRSDL rewards but I hadn't been claimed for quite a few days. I tried to claim the available rewards and noticed once the transaction completed that there was still a balance available to claim and the amount claimed was small in comparison.

The tx ref for this first transaction is - https://rinkeby.etherscan.io/tx/0x166fd1563ab3b254053a130d3232be561f46858a180a98fb661fc11a8d7edeec

I didn't get a screenshot for this first one as wasn't expecting it to fail.

Anyway, I tried to claim again and whilst the transaction worked with no errors, the unclaimed balance was not claimed.

The tx ref for this transaction is - https://rinkeby.etherscan.io/tx/0x9846a989b820e7482f6a9ec0413d2d19f7a651f9fa7566597e3da479c2e4aea7

![Screenshot 2021-04-29 at 12 46 32](https://user-images.githubusercontent.com/82473057/116547713-2961fa80-a8eb-11eb-9bd5-5d188df45714.png)

I performed this claim twice further with the same result.

https://rinkeby.etherscan.io/tx/0x701b295faafc5b9d94cf56158bda97f07bdcca6831b050148e06aea4c1c1d60a
https://rinkeby.etherscan.io/tx/0x8281243a13e7e373fc6c6882330833596688526e50e0671e88488120bea52473

![Screenshot 2021-04-29 at 12 48 42](https://user-images.githubusercontent.com/82473057/116547767-3aab0700-a8eb-11eb-8c01-cfb1ef8dfb38.png)

**To Reproduce**
1. I simply tried to claim.
2. The first transaction was partially successful but left an unclaimed balance
3. Subsequent claims appeared to process successfully but did not actually claim the available balance
4. There is now a remaining balance which does not look like it can be claimed

**Expected behavior**
All available balance should be claimed.

**Screenshots**
See above but also included the Supply/Borrow state below.

![Screenshot 2021-04-29 at 12 51 26](https://user-images.githubusercontent.com/82473057/116548017-8e1d5500-a8eb-11eb-8f46-a06163b5b5f6.png)

Current unclaimed balance

![Screenshot 2021-04-29 at 13 06 44](https://user-images.githubusercontent.com/82473057/116548223-d472b400-a8eb-11eb-9cac-bf97345e71e3.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3
- browser/version : Version 90.0.4430.85 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.4.0
- Test wallet : 0x46FFB3a528b3CCfb7fE590fE0f843f3fd57e6075

**Additional context**
Happy to perform a zoom screen share of that helps.

**Comment by ReluctantHodler** [comment]
Performed a hard refresh of the browser and it failed again.

https://rinkeby.etherscan.io/tx/0x356061687af512ccd36fd7c1a4f9795136af39384c0369a4c1504f1cda23f956

**Comment by ReluctantHodler** [comment]
Same issue on another wallet. I have recorded the screen. Claims a small amount and leaves bulk of balance unclaimed.

Wallet - 0x9B0Fff2102d23D25F541684c8109EFa7D91EE11c
Tx - https://rinkeby.etherscan.io/tx/0x35af6a3bef3ad0433228e4f19cec7856c15b12df56799f823de436adeeb7af2b

Screenshare was too big to drop in here so have uploaded to my Google Drive - https://drive.google.com/file/d/1uGJpLLzLoh3qE4oVoXZfc3vJy3OFcqTz/view?usp=sharing

**Comment by ryanmmmmm** [comment]
staging was out of eRSDL in the wallet to give rewards, we will always have a littl; erewards even after onboarding phase we will nto run into this

**Comment by ReluctantHodler** [comment]
I can confirm I was able to claim all available eRSDL rewards for both wallets. Let me know @ryanmmmmm if you want em to close the issue or leave open until you look at the question above? You could move to a triage or question status if you have one

**Comment by hskainth** [comment]
@ReluctantHodler  budget account will be monitored and alerts in place so this will not occur. This issue can be closed.

**Comment by LearnPolkadot** [comment]
Closing this issue per Dev team request.
