### ISSUE TITLE
Accrued not displayed on Borrow Market

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#40]
**Describe the bug**
On the borrow market the Accrued amount is not showing data.  See screenshot below:

**To Reproduce**
1. Go to ![image](https://user-images.githubusercontent.com/71201055/117035706-a2d66000-acd2-11eb-8fb9-7ab7e7c93ee9.png)
2. Borrow an asset from the Borrow Market
3. On the borrow market grid you will see no accrued data is displayed

**Expected behavior**
To see and accrued amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/71201055/117035790-be416b00-acd2-11eb-8ed0-b96e1509d422.png)

**Desktop (please complete the following information):**
OS: Windows 10 Pro - 20H2
Browser: Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Wallet Version (please complete the following information):
MM - MetaMask - 9.3.0

**Additional context**

**Comment by hskainth** [comment]
@LearnPolkadot  This is not a bug but a design decision that has already been raised internally 355 and closed. Please close issue.
