### ISSUE TITLE
Existing supply / borrow vanished - seemingly on addition of 'tool-tips'

### ISSUE THREAD

**Issue by oppoman** [UnFederalReserve/ReserveLendingAlphaTesters#41]
**Describe the bug**
As recently as yesterday (5/4/2021) I had been supplying ETH and eRSDL as well as borrowing USDC.  
I entered the staging page today and saw some new tool-tips describing what things are (great!) but my supply/borrow stakes have vanished.

In addition, the funds that I *was* supplying have also vanished and were not put back into the wallet (which is fine as this is just test funds, but still unexpected)

**To Reproduce**
Tough to describe as I didn't do anything to affect this change (afaik).

**Expected behavior**
I expected to still be supplying my ETH and eRSDL when refreshing the page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Wallet Version (please complete the following information):**
 - Wallet: Metamask
 - Public Address: 0x22F31317C384A892902a3Cb726516c04F857eCC8

**Additional context**
Things that I can remember that might be useful:
- Last I looked I owed ~$0.60 on a borrow loan that I had taken in USDC.  I didn't have enough USDC supplied to fully pay off that loan.
- I had plenty of ETH and eRSDL on the supply side
- I was supplying all of my eRSDL (whatever that amount was I don't recall)
- I verified that I was on the Rinkeby test network and that I was using the appropriate 'test' wallet in metamask.

**Comment by hskainth** [comment]
@oppoman thanks for raising, this is not an issue as site was updated yesterday and essentially reset values to default. please close.
