### ISSUE TITLE
Data displayed after wallet disconnected

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#5]
**Describe the bug**
After disconnecting a wallet data is still being displayed on the screen in the UI though the message "We are unable to show you any data before you will connect your wallet to the app" is displayed and wallet is no longer connected. (see attached screenshot)

**To Reproduce**
1.	Disconnect wallet
Note: Tested with both CB & MM wallets

**Expected behavior**
No data to be displayed

**Screenshots**
attached

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 20H2
 - Browser: Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)

**Wallet Version (please complete the following information):**
MM - MetaMask - 9.3.0
CB - Coinbase - 23.6.363

![image](https://user-images.githubusercontent.com/71201055/114511956-8df03a80-9c06-11eb-87d9-f466aae5bd90.png)

**Comment by hskainth** [comment]
Internal issue #337 raised

**Comment by hskainth** [comment]
@LearnPolkadot this has been fixed and verified internally please close.

**Comment by LearnPolkadot** [comment]
Thanks @hskainth
