### ISSUE TITLE
Supply Market data displayed after withdrawing

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#6]
**Describe the bug**
Assets are still showing up in the supply market table after assets have been removed.

**To Reproduce**
1.	Supply Asset (ex. eRSDL)
2.	Withdrawal Asset max 
3.	Asset still shows up in the Supply Market table 

**Expected behavior**
Assets not being supplied to the Supply Market not to show up in the supply market table

**Screenshots**
attached

Desktop (please complete the following information):

OS: Windows 10 Pro - 20H2
Browser: Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Wallet Version (please complete the following information):
MM - MetaMask - 9.3.0
CB - Coinbase - 23.6.363

![image](https://user-images.githubusercontent.com/71201055/114512258-e9222d00-9c06-11eb-9c6f-8ffa938464c0.png)

**Comment by harv-singh** [comment]
Hi @LearnPolkadot if you hover over the 0.00 balance a tool tip should show, what does this figure show? 
Example
<img width="276" alt="Screenshot 2021-04-14 at 13 27 30" src="https://user-images.githubusercontent.com/44998024/114710047-31377180-9d25-11eb-93ce-709252382113.png">

**Comment by LearnPolkadot** [comment]
Hello @harv-singh thanks for looking into this!   Attached is a screenshot that shows balance as requested ($0.00).  Also here is the address of the test account I am using if of any help 0xa1a955997A1827F93F6D124b57C411cFcFa3E769

![image](https://user-images.githubusercontent.com/71201055/114734011-d6484f00-9d11-11eb-8d6b-a4f7e956cede.png)

**Comment by harv-singh** [comment]
Thanks, we have an existing bug raised for this #287

**Comment by hskainth** [comment]
@LearnPolkadot this has been fixed and verified internally, please close.

**Comment by LearnPolkadot** [comment]
Thanks @hskainth
