### ISSUE TITLE
Asynchronous data

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#7]
**Describe the bug**
Currently on https://app.unfederalreserve.com/farms/eRSDL-ETH%20UNI-V2%20LP the data is asynchronous and automatically updates without the page being loaded.  Noticed none of the data on the Reserve Lending platform refreshes after an action nor does the Rewards updates as they do every block on the LP app.

**To Reproduce**
1. Complete a transaction

**Expected behavior**
Data in the application to be updated

**Screenshots**
attached

Desktop (please complete the following information):

OS: Windows 10 Pro - 20H2
Browser: Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Wallet Version (please complete the following information):
MM - MetaMask - 9.3.0
CB - Coinbase - 23.6.363

![image](https://user-images.githubusercontent.com/71201055/114512552-3c947b00-9c07-11eb-8480-fc4eb2e0cc65.png)
![image](https://user-images.githubusercontent.com/71201055/114512573-41592f00-9c07-11eb-9f61-e5ba7425b0ec.png)

**Comment by vladyslav2** [comment]
Partially fixed during today deploy to stage

**Comment by ReluctantHodler** [comment]
Does this cover this suggestion?

Suggestion to have the screen refresh after any 'dialog' is closed, as of now you need to manually refresh

**Comment by harv-singh** [comment]
Pleas recheck on stage now and close:


https://user-images.githubusercontent.com/44998024/115887198-9c7df380-a449-11eb-894e-3c7c2fe192c2.mov

**Comment by LearnPolkadot** [comment]
Awesome!  Confirmed on my side as well.  Also noted the unclaimed rewards data refreshes as well.  Great work @harv-singh
