### ISSUE TITLE
Wording when wallet disconnected (SP error)

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/ReserveLendingAlphaTesters#9]
**Is your feature request related to a problem? Please describe.**
When a wallet is disconnected the following message is displayed under Please connect wallet 
"We are unable to show you any data before you will connect your wallet to the app".
Not quite sure this is even a sentence (not a grammar major).

**Describe the solution you'd like**
Change wording to.
Please connect a wallet
In order to view data in the Reserve Lending application

![image](https://user-images.githubusercontent.com/71201055/114513021-bc224a00-9c07-11eb-9d17-e9c0d37e841c.png)

**Comment by Jag1899** [comment]
Internally raised #338

**Comment by hskainth** [comment]
@LearnPolkadot  Verified internally as fixed, please close issue.

**Comment by LearnPolkadot** [comment]
Thanks @hskainth

**Comment by LearnPolkadot** [comment]
> @LearnPolkadot Verified internally as fixed, please close issue.

Have these changes been pushed to https://ledger-stage.unfederalreservetesting.com/ ?  If not will they be (just curious)?
